#@start()
##################
#Travis-CI support
##################

#******************
#The Travis-CI file
#******************

# This file tells our external website for continuous integration, Travis-CI, how to perform the tests.
#@code()
# in which language the script was written
language: python
sudo: required
# on which operating systems the tests should be performed
os:
  - linux
# which Python releases to use
python:
  - "3.4"
  - "3.5"
# command to install dependencies and the script itself
install:
  - "python setup.py install"
  - "pip install sphinx_rtd_theme"
  - "sudo apt-get install graphviz"
  - "pip install travis-sphinx"
# command to run tests
script:
  - python -m unittest discover
  - travis-sphinx --source=documentation/source --branches=antiweb_testdoc,work build

after_success:
  - travis-sphinx --branches=antiweb_testdoc,work deploy
#@edoc()
